### ISSUE TITLE
Example initialization code.

### ISSUE THREAD

**Issue by adralien** [vorbeiei/kelctl#2]
The example initialization code doesn't work for me,

Installing from PIP gives a module of kelctl, not KELSerial,
The initializer of KELSerial won't work with a blank baud rate. 
BaudRate  is actually a class of kelctl, and must be imported as well or the constructor fails.

This worked for me:

from kelctl import KELSerial,BaudRate

rate = BaudRate.R115200

with KELSerial('COM23',rate) as load:
    print("Model: ", load.model)
    print("Status: ", load.status)

**Comment by vorbeiei** [comment]
Overlooked that in the documentation, latest version should now default properly to Baudrate of 115200.
In general I would recommend to just use:
`from kelctl import *`
